title: Grav Documentation
description: 'Grav documentation'

author:
  name: Andy Miller
  email: 'andy@getgrav.org'

taxonomies: [category,tag]
summary:
  size: 300

github:
  tree: https://github.com/getgrav/grav-learn/blob/develop/
  commits: https://github.com/getgrav/grav-learn/commits/develop/
