home:
  alias: '/basics'

pages:
  theme: learn
  markdown_extra: true
  process:
    markdown: true
    twig: false

cache:
  enabled: true
  check:
    pages: true
  driver: apc
  prefix: 'g'

twig:
  cache: true
  debug: false
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true


debugger:
  enabled: true
  log:
    enabled: false
    timing: false
