home:
  alias: '/basics'

pages:
  theme: learn4
  markdown:
    extra: true
  process:
    markdown: true
    twig: false
  hide_empty_folders: true

languages:
    supported: [15,16]
    pages_fallback_only: true

cache:
  enabled: false
  check:
    method: folder
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: false
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true
  collections:
      jquery: system://assets/jquery/jquery-3.x.min.js

errors:
  display: 1

images:
  prettyname_prefix: false

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
